//游戏日历下拉观看内容
$(".gameCalendarList2").mouseenter(function(){
    $(".gameCalendarList2-push").stop().slideDown()
});
$(".gameCalendarList2").mouseleave(function(){
    $(".gameCalendarList2-push").stop().slideUp()
});
$(".gameCalendarList3").mouseenter(function(){
    $(".gameCalendarList3-push").stop().slideDown()
});
$(".gameCalendarList3").mouseleave(function(){
    $(".gameCalendarList3-push").stop().slideUp()
});
$(".gameCalendarList4").mouseenter(function(){
    $(".gameCalendarList4-push").stop().slideDown()
});
$(".gameCalendarList4").mouseleave(function(){
    $(".gameCalendarList4-push").stop().slideUp()
});
$(".gameCalendarList5").mouseenter(function(){
    $(".gameCalendarList5-push").stop().slideDown()
});
$(".gameCalendarList5").mouseleave(function(){
    $(".gameCalendarList5-push").stop().slideUp()
});
$(".gameCalendarList6").mouseenter(function(){
    $(".gameCalendarList6-push").stop().slideDown()
});
$(".gameCalendarList6").mouseleave(function(){
    $(".gameCalendarList6-push").stop().slideUp()
});

